python -m main.main_hybrid_query `
    --csv random_queries_csv\Linq-AI-Research_FinDER-300-01.csv `
    --data-dir data\10k\converted `
    --default-year 2023 `
    -p full_10k `
    --column query `
    --id-column query_id `
    --output-csv `
    --concurrent 10 `
    --rerank-use-local `
    --rerank-local-workers 10